ts-safeql/safeql

demos/basic-migrations-raw/migrations/0.sql, demos/basic-migrations-raw/migrations/1.sql, demos/basic/src/setup.ts, demos/multi-connections/migrations_client1/0.sql, demos/multi-connections/migrations_client1/1.sql, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/generate/src/generate.test.ts
Hi @Newbie012, thanks again for making this public!
Just a quick PR to switch from serial fields to identity fields, since PostgreSQL doesn't recommend using serial going forward:
https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial
=> Switch from serial to identity fields

packages/eslint-plugin/src/rules/check-sql.test.ts
fixes https://github.com/ts-safeql/safeql/issues/4
=> add tests for conditional expressions

.changeset/big-beers-float.md, packages/eslint-plugin/CHANGELOG.md, packages/eslint-plugin/package.json
=> Revert "Version Packages"

.changeset/funny-cooks-fail.md, demos/basic/src/index.ts, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/rules/check-sql.utils.ts, packages/eslint-plugin/src/utils/ts.utils.ts
=> allow to compare against type reference

.changeset/wet-kangaroos-care.md, demos/basic-transform-type/.eslintrc.json, demos/big-project/safeql.config.ts, demos/from-config-file/safeql.config.ts, demos/postgresjs-demo/.eslintrc.json, demos/prisma/.eslintrc.json, docs/CHANGELOG.md, docs/api/index.md, docs/compatibility/postgres.js.md, docs/compatibility/prisma.md, packages/eslint-plugin/CHANGELOG.md, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/rules/check-sql.utils.ts
=> rename ${type} to {type}

.changeset/slow-ads-own.md, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.utils.ts
=> lint only typescript files

.changeset/spicy-schools-invite.md, demos/basic-migrations-raw/migrations/0.sql, demos/basic-migrations-raw/src/index.ts, docs/.vitepress/config.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/utils/ts-pg.utils.ts, packages/shared/src/common.ts
fixes https://github.com/ts-safeql/safeql/issues/123
=> add support for default types

.changeset/strange-moles-laugh.md, docs/.vitepress/config.ts, docs/api/index.md, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.test.ts
closes https://github.com/ts-safeql/safeql/issues/144
=> add support for skipTypeAnnotations

.changeset/twenty-yaks-accept.md, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/utils/ts-pg.utils.ts
fixes https://github.com/ts-safeql/safeql/issues/145
=> fix insert nullable to nullable column

docs/.vitepress/config.ts, docs/compatibility/slonik.md
Added a guide on how to start using SafeQL with Slonik 😃
=> Added slonik guide to docs

docs/.vitepress/config.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/utils/ts-pg.utils.ts
fixes https://github.com/ts-safeql/safeql/issues/151
=> fix only-null type insertion

.changeset/breezy-readers-dream.md, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/utils/get-type-properties.ts, packages/eslint-plugin/src/utils/ts.utils.ts
fixes https://github.com/ts-safeql/safeql/issues/156
=> fix type check with derived types

.changeset/tall-taxis-breathe.md, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/utils/ts-pg.utils.ts, packages/eslint-plugin/src/utils/ts.utils.ts
=> feat(eslint-plugin): add support for select statements with (type | null)[] expressions

.changeset/kind-peas-battle.md, packages/generate/src/utils/get-relations-with-joins.test.ts, packages/generate/src/utils/get-relations-with-joins.ts
Fixes https://github.com/ts-safeql/safeql/issues/176
=> Improve join expressions detections

.changeset/fast-snakes-notice.md, packages/generate/src/generate.test.ts, packages/generate/src/utils/get-relations-with-joins.ts, pnpm-lock.yaml
fixes https://github.com/ts-safeql/safeql/issues/180
=> feat: fix issue when selecting from a subselect with a join

docs/compatibility/node-postgres.md, docs/compatibility/prisma.md, docs/compatibility/sequelize.md, docs/compatibility/slonik.md
Fixed eslint config targets not being an array in some docs in compatibility
=> [docs] Fix eslint config in compatibility

.changeset/little-knives-flash.md, docs/.vitepress/config.ts, docs/api/index.md, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/generate/src/ast-describe.ts, packages/generate/src/generate.ts, pnpm-lock.yaml
Closes https://github.com/ts-safeql/safeql/issues/212
More info - https://github.com/ts-safeql/safeql/issues/212#issuecomment-2083712501
=> feat: override column types

.changeset/fifty-cobras-wash.md, docs/.vitepress/config.ts, docs/api/index.md, package.json, packages/eslint-plugin/src/rules/RuleOptions.ts, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.test.ts, pnpm-lock.yaml
closes https://github.com/ts-safeql/safeql/issues/226
This commit introduces a new  option in  which allows for deeper sql tag lookup when using . This is particularly useful for handling nested queries. The documentation has been updated to reflect this change and tests have been added to ensure its functionality.
=> feat: Add maxDepth option in connections.targets

.changeset/sharp-ghosts-drum.md
Create a changeset for the merged PR:
- #259
=> Create changeset for #259

README.md, docs/guide/getting-started.md
Added prerequisites for Windows OS.
=> Added node-gyp prerequisites for Windows and other OSes

.changeset/giant-flowers-crash.md, packages/eslint-plugin/src/rules/check-sql.test.ts, packages/eslint-plugin/src/utils/get-resolved-target-by-type-node.ts
fixes https://github.com/ts-safeql/safeql/issues/242
=> fix: correct issue with boolean union type inference

packages/generate/src/ast-get-sources.ts, packages/generate/src/generate.test.ts
fixes https://github.com/ts-safeql/safeql/issues/273
=> fix: correct non nullable column consideration

docs/compatibility/slonik.md
=> Correct syntax for supporting Slonik

.changeset/forty-tips-leave.md, packages/generate/src/generate.test.ts, packages/generate/src/utils/get-relations-with-joins.ts
fixes https://github.com/ts-safeql/safeql/issues/284
=> fix: select from nested join expression

.changeset/short-wombats-trade.md, packages/eslint-plugin/src/rules/check-sql.rule.ts, packages/eslint-plugin/src/rules/check-sql.utils.ts, packages/eslint-plugin/src/utils/is-in-editor.ts
closes https://github.com/ts-safeql/safeql/issues/349
=> feat: fail gracefully on fatal error
